---
deployment:
  tasks:
    - export DEPLOYPATH=/home/intiestu/public_html/
    
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp index2.html $DEPLOYPATH

   